### ISSUE TITLE
Discuss transfer ownership to @raviqqe

### ISSUE THREAD

**Issue by femtomc** [mlir-rs/mlir-sys#51]
Hi @raviqqe -- I'm increasingly busy with work outside of Rust (and other academic work, which is preventing me from giving this repository its due support).

Wdyt about a transfer of ownership?

If you _don't_ want this, I'm also happy keeping things as is -- I just wanted to raise the option in case you wanted to take over.

**Comment by raviqqe** [comment]
Yeah, we can do that or we can have some organization together. But I'm not sure if we have enough people to develop together...?

cc @edg-l

**Comment by edg-l** [comment]
A github org would be nice, maybe something like mlir-rs orntge like, i have time to keep things updated since I use these libraries at work

**Comment by edg-l** [comment]
any news on this?

**Comment by raviqqe** [comment]
@edg-l Sounds good to me! @femtomc ?

**Comment by femtomc** [comment]
I'll crete a GitHub org today! Sorry for delay.

**Comment by femtomc** [comment]
Moved the package under the new (mlir-rs) and I’ve invited active contributors as members.

**Comment by raviqqe** [comment]
Thank you! Can you make me and @edg-l organization owners for continuity too?

**Comment by femtomc** [comment]
Absolutely!

**Comment by edg-l** [comment]
programmer png editing skills (maybe a temporary logo for the organization :P)

![MLIR_Logo svg(1)](https://github.com/user-attachments/assets/b4e75bc0-eb1b-4dea-83ea-95735cd1836c)

**Comment by edg-l** [comment]
@raviqqe i transfered here tblgen-rs-alt too

**Comment by femtomc** [comment]
Doing it now, sorry for delay!

**Comment by femtomc** [comment]
Okay, should be all set! Try again (tell me if it didn't work, so I can try the role magic again).

**Comment by raviqqe** [comment]
@femtomc @edg-l I just moved Melior to the organization!

@femtomc It looks like the roles haven't changed yet. Can you check that again? I'm talking about this page on GitHub documentation btw. https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization

<img width="989" alt="Screenshot 2024-12-03 at 19 26 31" src="https://github.com/user-attachments/assets/e8eda800-342a-4cc5-8d91-2b8e7c7586c5">

**Comment by raviqqe** [comment]
I just sent ownership invitation to the `melior` crate on the crates.io.

**Comment by femtomc** [comment]
Okay, now all set for real :)

**Comment by raviqqe** [comment]
@femtomc Thank you so much!
